#datasource
spring:
  datasource:
    url: jdbc:mysql://10.0.0.73:33306/test02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    username: test02
    password: test02

  redis:
    host: 10.0.0.15
    database: 7
